name: Build Check

on:
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd web
          npm install
          npm run build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0
      - name: Setup Virtual Environment
        run: |
          cd ..
          python -m venv venv
      - name: Activate Virtual Environment
        run: |
          ./venv/Scripts/activate
      - name: Install Python Dependencies 
        run: |
          pip install -r requirements.txt
      - name: Build Project
        run: |
          pyinstaller --onefile --noconsole --icon='./web/dist/favicon.ico' --add-data='./web/dist/;./web/dist/' main.py
      - name: deactivate Virtual Environment
        run: |
          deactivate
