name: Build Check

on:
  push:
    branches:
      - main  # Replace with the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd web
          npm install
          npm run build
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3
      - name: Install Python Dependencies 
        run: |
          pip install -r ./requirements.txt
      - name: Build Project
        run: |
          pyinstaller --onefile --noconsole --icon='./web/dist/favicon.ico' --add-data='./web/dist/:./web/dist/' main.py
